# Generated by Django 5.2 on 2025-04-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
