# Generated by Django 5.2 on 2025-05-03 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendarapp', '0003_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('calendar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='calendarapp.calendar')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringStudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrence_amount', models.IntegerField()),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_sessions', to='study_sessions.studysession')),
            ],
        ),
        migrations.CreateModel(
            name='StudySessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions_participated', to=settings.AUTH_USER_MODEL)),
                ('study_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_set', to='study_sessions.studysession')),
            ],
        ),
    ]
