# Generated by Django 5.1.7 on 2025-03-27 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
        ('study_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='calendar_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='calendarapp.calendar'),
            preserve_default=False,
        ),
    ]
