# Generated by Django 5.2.1 on 2025-05-13 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringstudysession',
            name='recurrence_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='studysessionparticipant',
            constraint=models.UniqueConstraint(fields=('study_session', 'participant'), name='unique_participation'),
        ),
    ]
