# Generated by Django 5.1.7 on 2025-03-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0002_studysession_calendar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
