# Generated by Django 5.1.7 on 2025-03-29 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0003_alter_studysession_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringStudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrence_amount', models.IntegerField()),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_sessions', to='study_sessions.studysession')),
            ],
        ),
    ]
